### ISSUE TITLE
"run local tests" not showing as completed 

### ISSUE THREAD

**Issue by carriemathieu** [learn-co-curriculum/react-event-system-lab#14]
all tests passing & lesson submitted, but "run local tests" not showing as completed. not giving option for "next lesson" (have to navigate via course dropdown menu) and not showing completed in course dropdown menu. lesson doesn't show as started in dropdown menu.

**Comment by lexisandoval** [comment]
Having the same issue as above

**Comment by Emanao** [comment]
Tests did pass but the test process could not finish, therefore  "run local tests"  didnt show as completed. See Traceback below after interrupting the process.
My workaround: Changing my node version from 16.0.0 to 10 > nvm use 10 

^CTraceback (most recent call last):
        7: from /Users/emanao/.rvm/gems/ruby-2.6.1/bin/learn-test:23:in `<main>'
        6: from /Users/emanao/.rvm/gems/ruby-2.6.1/bin/learn-test:23:in `load'
        5: from /Users/emanao/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/bin/learn-test:73:in `<top (required)>'
        4: from /Users/emanao/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/lib/learn_test/runner.rb:17:in `run'
        3: from /Users/emanao/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/lib/learn_test/strategies/mocha.rb:23:in `run'
        2: from /Users/emanao/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/lib/learn_test/strategies/mocha.rb:65:in `run_mocha'
        1: from /Users/emanao/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/lib/learn_test/strategies/mocha.rb:77:in `run_node_based_mocha'
/Users/emanao/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/lib/learn_test/strategies/mocha.rb:77:in `system': Interrupt
